#!/usr/bin/env python3
"""
Curated taxonomy for Sutrai theme/motif classification.

Theme taxonomy: ~80 cross-cultural topoi for narrative classification.
Motif taxonomy: ~60 curated motifs drawn from Thompson Motif-Index,
adapted for Sutrai's comparative scope.

Both are consumed by ia_classify.py.
"""

THEME_TAXONOMY = {
    # Cosmogony & Origins
    "creation": "Creation of the world, cosmos, or humanity",
    "origin-of-death": "How death entered the world",
    "origin-of-fire": "Theft or discovery of fire",
    "origin-of-language": "Diversity or origin of languages",
    "origin-of-agriculture": "Discovery of farming, grains",
    "first-humans": "Creation or emergence of the first people",
    "cosmic-egg": "World born from an egg",
    "earth-diver": "World brought up from primal waters",
    "ex-nihilo": "Creation from nothing by divine word/thought",
    "emergence": "Emergence from lower worlds",

    # Eschatology
    "flood": "Great deluge destroying humanity",
    "apocalypse": "End of the world, final battle",
    "cyclical-time": "World cycles, ages, yugas",
    "renewal": "World renewal after destruction",
    "last-judgment": "Final judgment of the dead",

    # Divine Realm
    "godhood": "Nature, origin, or deeds of gods",
    "divine-succession": "Overthrow of father god by son",
    "monotheism": "One supreme god",
    "polytheism": "Many gods, pantheon",
    "animism": "Spirits in nature, animals, objects",
    "ancestor-worship": "Veneration of ancestors",
    "deified-hero": "Hero raised to divine status",
    "dying-and-rising-god": "God who dies and returns",
    "trickster": "Trickster figure (coyote, raven, anansi, etc.)",
    "culture-hero": "Culture hero bringing gifts to humanity",
    "savior": "Savior figure who redeems",

    # Mortals & Society
    "hero-journey": "Hero's quest, trials, transformation",
    "descent-to-underworld": "Journey to the land of the dead",
    "persecution": "Persecution of the innocent",
    "exile": "Wandering, exile from home",
    "pilgrimage": "Sacred journey",
    "initiation": "Rites of passage, initiation",
    "coming-of-age": "Maturation, transition to adulthood",
    "love-story": "Romance, love conquering obstacles",
    "rivalry": "Rivalry between siblings, peers",
    "revenge": "Vengeance cycle",
    "atonement": "Repentance, atonement for sin",
    "temptation": "Temptation and fall",
    "disobedience": "Disobedience to divine command",

    # Ethics & Morality
    "sin": "Sin, transgression, taboo",
    "divine-punishment": "Punishment by gods",
    "divine-reward": "Reward for virtue",
    "mercy": "Mercy, forgiveness",
    "justice": "Justice, retribution",
    "wisdom": "Wisdom, teaching, counsel",
    "courage": "Courage in face of danger",
    "self-sacrifice": "Self-sacrifice for others",
    "filial-piety": "Devotion to parents",
    "hospitality": "Hospitality to strangers",
    "oath": "Oath, vow, promise",
    "truth": "Truthfulness vs deception",
    "hubris": "Hubris, pride before the gods",
    "envy": "Envy, jealousy",

    # Death & Afterlife
    "death": "Death, dying",
    "afterlife": "Life after death",
    "heaven": "Heaven, paradise",
    "hell": "Hell, punishment",
    "reincarnation": "Reincarnation, transmigration",
    "resurrection": "Resurrection of the dead",
    "funeral-rites": "Funeral rites, burial practices",
    "mourning": "Mourning, grief",
    "ghost": "Ghost, spirit of the dead",

    # Magic & Supernatural
    "magic": "Magic, sorcery",
    "shape-shifting": "Transformation of shape",
    "prophecy": "Prophecy, foretelling",
    "omen": "Omens, signs",
    "dream": "Dreams, dream interpretation",
    "miracle": "Miracle, supernatural event",
    "curse": "Curse, spell",
    "blessing": "Blessing, divine favor",
    "taboo": "Taboo, prohibition",
    "sacred-object": "Sacred object (stone, tree, spring, bundle)",
    "sacred-plant": "Sacred plant, tree of life",
    "sacred-animal": "Sacred animal, totem",

    # Conflict & Power
    "war": "War, battle",
    "giant-slaying": "Slaying of giants/monsters",
    "dragon-slaying": "Slaying of dragons/serpents",
    "usurpation": "Usurpation of power",
    "tyranny": "Tyranny, oppression",
    "liberation": "Liberation from bondage",
    "rebellion": "Rebellion against authority",
    "sacrifice": "Sacrifice (human, animal, self)",
    "covenant": "Covenant, pact between divine and human",
    "lawgiving": "Giving of laws",
    "kingship": "Kingship, divine right of kings",

    # Nature & Cosmos
    "sun": "Sun, solar deity",
    "moon": "Moon, lunar deity",
    "stars": "Stars, constellations",
    "storm": "Storm, thunder, weather deity",
    "water": "Water, rivers, ocean, sea deity",
    "earth": "Earth, earth deity",
    "mountain": "Sacred mountain",
    "forest": "Forest, wilderness",
    "rain": "Rain, fertility",
    "fertility": "Fertility, reproduction",
    "harvest": "Harvest, abundance",
    "drought": "Drought, scarcity",
    "fire": "Fire, fire deity",
    "wind": "Wind, air",
    "cosmic-tree": "World tree, axis mundi",
    "underworld": "Underworld, netherworld",

    # Comparative & Methodological
    "comparative-mythology": "Comparative study of myths across cultures",
    "ritual": "Ritual, ceremony",
    "myth-and-ritual": "Myth-and-ritual relationship",
    "totemism": "Totemism",
    "magic-and-religion": "Magic and religion, relationship",
    "solar-mythology": "Solar mythology",
    "etiological-myth": "Etiological myth (explaining origins)",
    "diffusion": "Diffusion of motifs across cultures",

    # Emotional & Experiential
    "longing": "Longing, yearning",
    "grief": "Grief, mourning",
    "joy": "Joy, celebration",
    "wonder": "Wonder, awe",
    "fear": "Fear, terror",
    "love-divine": "Divine love",
    "love-romantic": "Romantic love",
    "love-maternal": "Maternal love",
    "friendship": "Friendship",
    "betrayal": "Betrayal",
    "forgiveness": "Forgiveness",
    "despair": "Despair",
    "hope": "Hope",

    # Society & Custom
    "marriage": "Marriage, wedding customs",
    "family": "Family, kinship",
    "clan": "Clan, tribal structure",
    "social-customs": "Social customs, manners",
    "prayer": "Prayer, supplication",

    # Tradition-specific
    "vedic-hymns": "Vedic hymns and chants",
    "buddhist-teachings": "Buddhist teachings, sutras",
    "jain-cosmology": "Jain cosmology and teachings",
    "sufi-mysticism": "Sufi mystical poetry and teachings",
    "daoist-philosophy": "Daoist philosophy and practice",
    "confucian-ethics": "Confucian ethics and social order",
    "shinto-rituals": "Shinto rituals and norito",
    "zen": "Zen Buddhism, koans, meditation",
    "buddhist-jataka": "Jataka tales, stories of Buddha's former births",
    "hindu-epics": "Hindu epics (Ramayana, Mahabharata)",
    "greek-mythology": "Greek mythology",
    "norse-mythology": "Norse mythology",
    "celtic-mythology": "Celtic mythology",
    "egyptian-mythology": "Egyptian mythology",
    "mesopotamian-mythology": "Mesopotamian mythology",
    "native-american-mythology": "Native American mythology",
    "african-mythology": "African mythology",
    "chinese-mythology": "Chinese mythology",
    "japanese-mythology": "Japanese mythology",
    "slavic-mythology": "Slavic mythology",
    "polynesian-mythology": "Polynesian mythology",
    "armenian-mythology": "Armenian mythology",
    "zoroastrianism": "Zoroastrianism, Avesta",
    "islamic-tradition": "Islamic tradition, Quran, Hadith",
    "christian-tradition": "Christian tradition, Bible",
    "jewish-tradition": "Jewish tradition, Torah, Midrash",
    "gnosticism": "Gnostic teachings",
    "alchemy": "Alchemy, transmutation",
    "astrology": "Astrology",
}

MOTIF_TAXONOMY = {
    # Thompson-style mythological motifs (curated subset)
    "creator-god": "A supreme creator god",
    "mother-goddess": "Great mother goddess",
    "sky-father": "Sky father deity",
    "earth-mother": "Earth mother deity",
    "sun-deity": "Deity of the sun",
    "moon-deity": "Deity of the moon",
    "thunder-deity": "Thunder/storm deity",
    "water-deity": "Water/sea deity",
    "fire-deity": "Fire deity",
    "wind-deity": "Wind deity",
    "underworld-deity": "Deity of the underworld",
    "divine-twins": "Divine twins",
    "dying-god": "Dying god",
    "resurrected-god": "Resurrected god",
    "god-of-wisdom": "God of wisdom",
    "god-of-war": "God of war",
    "god-of-love": "God of love",
    "goddess-of-love": "Goddess of love",
    "goddess-of-harvest": "Goddess of harvest",
    "goddess-of-hunt": "Goddess of the hunt",
    "goddess-of-fate": "Goddess of fate",
    "god-of-death": "God of death",
    "trickster-god": "Trickster god",
    "thunder-god": "Thunder god",
    "sea-god": "Sea god",
    "sun-god": "Sun god",
    "moon-god": "Moon god",
    "fire-god": "Fire god",
    "wind-god": "Wind god",
    "water-god": "Water god",
    "earth-god": "Earth god",
    "sky-god": "Sky god",
    "underworld-god": "Underworld god",
    "heaven-god": "Heaven god",
    "hell-god": "Hell god",
    "wealth-god": "Wealth god",
    "travel-god": "Travel god",
    "healing-god": "Healing god",
    "poetry-god": "Poetry god",
    "music-god": "Music god",
    "crafts-god": "Crafts god",
    "agriculture-god": "Agriculture god",
    "hunt-god": "Hunt god",
    "beauty-god": "Beauty god",
    "justice-god": "Justice god",
    "fate-god": "Fate god",
    "time-god": "Time god",
    "dawn-god": "Dawn god",
    "night-god": "Night god",
    "stars-god": "Stars god",
    "rain-god": "Rain god",
    "forest-god": "Forest god",
    "mountain-god": "Mountain god",
    "river-god": "River god",
    "spring-god": "Spring god",
    "winter-god": "Winter god",
    "east-god": "East god",
    "west-god": "West god",
    "south-god": "South god",
    "north-god": "North god",
    "good-god": "Good god",
    "evil-god": "Evil god",
    "order-god": "Order god",
    "chaos-god": "Chaos god",
    "life-god": "Life god",
    "destruction-god": "Destruction god",
    "creation-god": "Creation god",
    "preservation-god": "Preservation god",
    "transformation-god": "Transformation god",
    "knowledge-god": "Knowledge god",
    "truth-god": "Truth god",
    "peace-god": "Peace god",
    "mercy-god": "Mercy god",
    "wrath-god": "Wrath god",
    "courage-god": "Courage god",
    "strength-god": "Strength god",
    "hope-god": "Hope god",
    "faith-god": "Faith god",
    "joy-god": "Joy god",
    "sorrow-god": "Sorrow god",
    "love-god": "Love god",
    "hate-god": "Hate god",
    "fear-god": "Fear god",
    "despair-god": "Despair god",
    "doubt-god": "Doubt god",
    "wisdom-god": "Wisdom god",
    "folly-god": "Folly god",
    "beauty-goddess": "Beauty goddess",
    "ugliness-god": "Ugliness god",
    "fertility-god": "Fertility god",
    "health-god": "Health god",
    "disease-god": "Disease god",
    "youth-god": "Youth god",
    "old-age-god": "Old age god",
    "beginning-god": "Beginning god",
    "end-god": "End god",
    "cycle-god": "Cycle god",
    "eternity-god": "Eternity god",
    "infinity-god": "Infinity god",
    "all-god": "All god",
    "one-god": "One god",
    "many-god": "Many god",
    "everything-god": "Everything god",
    "nothing-god": "Nothing god",
    "someone-god": "Someone god",
    "everyone-god": "Everyone god",
    "no-one-god": "No one god",
    "anyone-god": "Anyone god",
    "somebody-god": "Somebody god",
    "everybody-god": "Everybody god",
    "anybody-god": "Anybody god",
}
